version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: on-failure
    command: sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15.3-alpine
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/usr/share/nginx/doc
