# Generated by Django 4.2.3 on 2023-07-24 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?:(?!.*[эЭыЫ]))[А-яіІїЇґҐєЄ-]{2,50}$', ['Only Ukrainian letters or "-"', 'min 2 characters', 'max 50 characters'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Only numbers, 12 numbers')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?:(?!.*[эЭыЫ]))[А-яіІїЇґҐєЄ-]{2,50}$', ['Only Ukrainian letters or "-"', 'min 2 characters', 'max 50 characters'])]),
        ),
    ]
