# Generated by Django 4.2.3 on 2023-07-24 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilemodel_name_alter_profilemodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=(?:.*[`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]))[a-zA-Z\\d`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]{8,30}$', ['min 1 lowercase ch', 'min 1 uppercase ch', 'min 1 digit', 'min 1 special character', 'length 8-30'])], verbose_name='password'),
        ),
    ]
