# Generated by Django 4.2.7 on 2024-02-15 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$', 'Only latin letters min 2 max 20 ch')])),
            ],
            options={
                'db_table': 'course_names',
            },
        ),
    ]
