# Generated by Django 4.2.3 on 2023-07-31 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenamemodel',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$', 'Only letters min 2 max 20 ch')]),
        ),
    ]
