# Generated by Django 4.2.7 on 2024-02-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursemodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='name',
            new_name='course_name',
        ),
    ]
