# Generated by Django 4.2.7 on 2024-02-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_name_coursemodel_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='course_name',
            new_name='name',
        ),
    ]
