# Generated by Django 4.2.7 on 2024-02-15 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,11}$', 'Only latin letters min 2 max 11 ch')])),
                ('preview_playlist', models.URLField(blank=True, max_length=255)),
                ('courses', models.ManyToManyField(related_name='modules', to='courses.coursemodel')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
