# Generated by Django 4.2.7 on 2024-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='groups',
            field=models.ManyToManyField(related_name='modules', to='groups.groupmodel'),
        ),
    ]
