# Generated by Django 4.2.3 on 2023-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemodel',
            name='courses',
            field=models.ManyToManyField(to='courses.coursemodel'),
        ),
    ]
