# Generated by Django 4.2.7 on 2024-02-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupmodel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmodel',
            unique_together=set(),
        ),
    ]
