# Generated by Django 4.2.7 on 2024-02-15 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_alter_groupmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
