# Generated by Django 4.2.7 on 2024-02-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_name_coursemodel_course_name'),
        ('groups', '0008_alter_groupmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='name',
            new_name='group_name',
        ),
        migrations.AlterUniqueTogether(
            name='groupmodel',
            unique_together={('group_name', 'month', 'year')},
        ),
    ]
