# Generated by Django 4.2.7 on 2024-02-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_course_name_coursemodel_name'),
        ('groups', '0009_rename_name_groupmodel_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='groupmodel',
            unique_together={('name', 'month', 'year')},
        ),
    ]
